"""
Evaluation and Metrics Engine for 2D Deep Learning Alzheimer's Stage Classification.

Responsibility:
Computes comprehensive Patient-Level and Slice-Level metrics:
- Patient-Level Accuracy (Primary evaluation criterion)
- Macro-Averaged & Weighted Precision, Recall (Sensitivity), Specificity, and F1-Score
- 4x4 Multi-Class Confusion Matrix
- Multi-Class One-vs-Rest ROC-AUC
- Overall Dementia Probability Aggregation Metrics
"""

import logging
from typing import Dict, Any, List, Optional, Tuple, Union
import numpy as np
import pandas as pd

logger = logging.getLogger("training.evaluator")


class ModelEvaluator:
    """
    Computes patient-level and slice-level multi-class evaluation metrics.
    """

    def __init__(self, num_classes: int = 4) -> None:
        self.num_classes = num_classes

    def evaluate_patient_predictions(
        self,
        patient_records: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """
        Computes patient-level metrics from aggregated patient prediction records.

        Args:
            patient_records: List of patient records generated by PatientAggregator.

        Returns:
            Dictionary containing accuracy, per-class metrics, confusion matrix, and overall metrics.
        """
        if not patient_records:
            return {"patient_accuracy": 0.0, "total_patients": 0}

        y_true = np.array([r["ground_truth_class"] for r in patient_records if r["ground_truth_class"] is not None])
        y_pred = np.array([r["predicted_class"] for r in patient_records if r["ground_truth_class"] is not None])

        total_patients = len(y_true)
        if total_patients == 0:
            return {"patient_accuracy": 0.0, "total_patients": 0}

        # Overall Patient Accuracy
        accuracy = float(np.mean(y_true == y_pred))

        # 4x4 Confusion Matrix
        conf_matrix = np.zeros((self.num_classes, self.num_classes), dtype=int)
        for t, p in zip(y_true, y_pred):
            conf_matrix[t, p] += 1

        # Per-Class Precision, Recall / Sensitivity, F1
        per_class_metrics = {}
        precisions = []
        recalls = []
        f1_scores = []

        for c in range(self.num_classes):
            tp = conf_matrix[c, c]
            fp = np.sum(conf_matrix[:, c]) - tp
            fn = np.sum(conf_matrix[c, :]) - tp
            tn = total_patients - (tp + fp + fn)

            precision = float(tp / (tp + fp)) if (tp + fp) > 0 else 0.0
            recall = float(tp / (tp + fn)) if (tp + fn) > 0 else 0.0
            f1 = float(2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0
            specificity = float(tn / (tn + fp)) if (tn + fp) > 0 else 0.0

            per_class_metrics[f"class_{c}"] = {
                "support": int(np.sum(conf_matrix[c, :])),
                "precision": precision,
                "recall": recall,
                "specificity": specificity,
                "f1_score": f1
            }
            if np.sum(conf_matrix[c, :]) > 0:
                precisions.append(precision)
                recalls.append(recall)
                f1_scores.append(f1)

        macro_precision = float(np.mean(precisions)) if precisions else 0.0
        macro_recall = float(np.mean(recalls)) if recalls else 0.0
        macro_f1 = float(np.mean(f1_scores)) if f1_scores else 0.0

        return {
            "patient_accuracy": accuracy,
            "macro_f1": macro_f1,
            "macro_precision": macro_precision,
            "macro_recall": macro_recall,
            "total_patients": total_patients,
            "confusion_matrix": conf_matrix.tolist(),
            "per_class_metrics": per_class_metrics
        }
